import mongoose from "mongoose";

const listingSchema = new mongoose.Schema(
  {
    // field: id, data type: string, auto-generated by MongoDB
    // MongoDB will create _id automatically, but we can use it as id

    // field: title, data type: string, validation rules: required
    title: {
      type: String,
      required: true,
    },

    // field: company, data type: string, validation rules: required
    company: {
      type: String,
      required: true,
    },

    // field: duration, data type: string
    duration: {
      type: String,
    },

    // field: description, data type: string (optional)
    description: {
      type: String,
    },
  },
  { timestamps: true } // Adds createdAt and updatedAt fields automatically
);

// Export listing model
export default mongoose.model("Listings", listingSchema);